In [215]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [216]:
df = pd.read_excel('Rbi_Master_Data.xlsx')
df.head()

,Date,RTGS_Vol,RTGS_Val,NEFT_Vol,NEFT_Val,AePS_Vol,AePS_Val,UPI_Vol,UPI_Val,IMPS_Vol,...,NFS_ATM_Vol,NFS_ATM_Val,AePS_microATM_Vol,AePS_microATM_Val,Government_Securities_Clearing_Vol,Government_Securities_Clearing_Val,Forex_Clearing_Vol,Forex_Clearing_Val,Rupee_Derivatives_Vol,Rupee_Derivatives_Val
0,2024-04-01 00:00:00,0.76502,1.753363e+04,26.92938,30073.669396,0.36,12.65,4081.77,65707.52,240.94,...,105.90,4687.69,25.00,733.97,h,h,h,h,h,h
1,2024-04-02 00:00:00,13.07831,1.229851e+06,411.34372,219355.700292,0.56,19.74,4376.71,78992.68,256.87,...,118.28,5630.46,34.41,999.47,0.05842,788116.039,0.155675,580271.97,0.00683,42935
2,2024-04-03 00:00:00,10.59144,7.764763e+05,287.14959,139377.305542,0.58,19.82,4574.56,81612.52,201.07,...,127.31,6251.42,36.66,1045.44,0.05604,786404.092,0.125105,381483.23,0.00482,17435
3,2024-04-04 00:00:00,9.81395,7.345305e+05,265.44630,126111.835911,0.56,18.25,4637.32,80339.98,202.16,...,117.74,5653.52,34.87,961.44,0.06356,778661.89841,0.086655,303460.19,0.00708,85735
4,2024-04-05 00:00:00,10.00607,6.990589e+05,287.18951,137545.517042,0.54,16.96,4683.52,76592.44,201.99,...,115.57,5428.63,34.68,919.54,0.06065,804176.641541,0.126695,347608.78,0.0063,46230

In [217]:
df.shape

(868, 43)

In [218]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 868 entries, 0 to 867
Data columns (total 43 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Date                                868 non-null    object
 1   RTGS_Vol                            868 non-null    float64
 2   RTGS_Val                            868 non-null    float64
 3   NEFT_Vol                            868 non-null    float64
 4   NEFT_Val                            868 non-null    float64
 5   AePS_Vol                            868 non-null    float64
 6   AePS_Val                            868 non-null    float64
 7   UPI_Vol                             868 non-null    float64
 8   UPI_Val                             868 non-null    float64
 9   IMPS_Vol                            868 non-null    float64
 10  IMPS_Val                            868 non-null    float64
 11  NACH Credit_Vol                     868 non-null    float64
 12  NACH Credit_Val                     868 non-null    float64
 13  NACH Debit_Vol                      868 non-null    float64
 14  NACH Debit_Val                      868 non-null    float64
 15  NETC_Vol                            868 non-null    float64
 16  NETC_Val                            868 non-null    float64
 17  BBPS_Vol                            868 non-null    float64
 18  BBPS_Val                            868 non-null    object
 19  CTS_Vol                             868 non-null    object
 20  CTS_Val                             868 non-null    object
 21  CreditCard_POS_Vol                  868 non-null    float64
 22  CreditCard_POS_Val                  868 non-null    object
 23  CreditCard_Ecommerce_Vol            487 non-null    float64
 24  CreditCard_Ecommerce_Val            868 non-null    float64
 25  DebitCard_POS_Vol                   868 non-null    float64
 26  DebitCard_POS_Val                   868 non-null    float64
 27  DebitCard_Ecommerce_Vol             487 non-null    float64
 28  DebitCard_Ecommerce_Val             868 non-null    float64
 29  PPI_POS_Vol                         868 non-null    float64
 30  PPI_POS_Val                         868 non-null    float64
 31  PPI_Ecommerce_Vol                   487 non-null    float64
 32  PPI_Ecommerce_Val                   868 non-null    float64
 33  NFS_ATM_Vol                         868 non-null    float64
 34  NFS_ATM_Val                         868 non-null    float64
 35  AePS_microATM_Vol                   868 non-null    float64
 36  AePS_microATM_Val                   868 non-null    float64
 37  Government_Securities_Clearing_Vol  868 non-null    object
 38  Government_Securities_Clearing_Val  868 non-null    object
 39  Forex_Clearing_Vol                  868 non-null    object
 40  Forex_Clearing_Val                  868 non-null    object
 41  Rupee_Derivatives_Vol               868 non-null    object
 42  Rupee_Derivatives_Val               868 non-null    object
dtypes: float64(32), object(11)
memory usage: 291.7+ KB

In [219]:
df.columns.tolist()

['Date',
 'RTGS_Vol',
 'RTGS_Val',
 'NEFT_Vol',
 'NEFT_Val',
 'AePS_Vol',
 'AePS_Val',
 'UPI_Vol',
 'UPI_Val',
 'IMPS_Vol',
 'IMPS_Val',
 'NACH Credit_Vol',
 'NACH Credit_Val',
 'NACH Debit_Vol',
 'NACH Debit_Val',
 'NETC_Vol',
 'NETC_Val',
 'BBPS_Vol',
 'BBPS_Val',
 'CTS_Vol',
 'CTS_Val',
 'CreditCard_POS_Vol',
 'CreditCard_POS_Val',
 'CreditCard_Ecommerce_Vol',
 'CreditCard_Ecommerce_Val',
 'DebitCard_POS_Vol',
 'DebitCard_POS_Val',
 'DebitCard_Ecommerce_Vol',
 'DebitCard_Ecommerce_Val',
 'PPI_POS_Vol',
 'PPI_POS_Val',
 'PPI_Ecommerce_Vol',
 'PPI_Ecommerce_Val',
 'NFS_ATM_Vol',
 'NFS_ATM_Val',
 'AePS_microATM_Vol',
 'AePS_microATM_Val',
 'Government_Securities_Clearing_Vol',
 'Government_Securities_Clearing_Val',
 'Forex_Clearing_Vol',
 'Forex_Clearing_Val',
 'Rupee_Derivatives_Vol',
 'Rupee_Derivatives_Val']

In [220]:
df.isnull().sum().sum()

np.int64(1143)

In [221]:
df.duplicated().sum()

np.int64(0)

In [222]:
df.duplicated().sum()

np.int64(0)

In [223]:
df.describe(include= "all")

,Date,RTGS_Vol,RTGS_Val,NEFT_Vol,NEFT_Val,AePS_Vol,AePS_Val,UPI_Vol,UPI_Val,IMPS_Vol,...,NFS_ATM_Vol,NFS_ATM_Val,AePS_microATM_Vol,AePS_microATM_Val,Government_Securities_Clearing_Vol,Government_Securities_Clearing_Val,Forex_Clearing_Vol,Forex_Clearing_Val,Rupee_Derivatives_Vol,Rupee_Derivatives_Val
count,868,868.000000,8.680000e+02,868.000000,868.000000,868.000000,868.000000,868.000000,868.000000,868.000000,...,868.000000,868.000000,868.000000,868.000000,868,868,868,868,868,868
unique,868,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,594,738,547,589,439,565
top,2026-08-16 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,h,h,h,h,h,h
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,231,129,231,231,231,231
mean,NaN,9.169360,6.010670e+05,272.238696,132017.351428,0.678275,22.034551,6132.176555,81660.571106,140.549401,...,90.840680,2369.884049,32.154539,2182.671774,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,4.372282,4.026582e+05,74.532831,72428.472637,0.168516,5.426678,1058.838242,15723.106642,23.920108,...,11.996692,2115.119366,6.663376,1597.583353,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,0.765020,1.134922e+04,26.929380,14445.232629,0.264000,9.510000,4081.770000,45136.000000,84.740000,...,66.390000,7.267640,17.170000,468.430000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,5.863040,1.450922e+05,223.076510,82060.755881,0.569000,18.635000,5217.925000,70375.195000,123.745000,...,81.852500,66.930823,27.527500,781.900000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,10.466685,7.360152e+05,275.180455,144969.151157,0.669000,20.975000,6120.320000,80482.980000,139.250000,...,89.950000,3316.465000,31.145000,1008.100000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,12.196715,8.713546e+05,314.233210,170566.339505,0.768000,24.130000,7054.710000,92678.527500,155.445000,...,98.410000,4221.562500,35.192500,3730.477500,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,25.833120,2.454674e+06,579.278180,597085.590509,1.579000,48.160000,8487.910000,131735.460000,256.870000,...,142.430000,6984.180000,70.910000,5912.820000,NaN,NaN,NaN,NaN,NaN,NaN

In [224]:
df['Date'] = pd.to_datetime(df['Date'])

In [225]:
df.dtypes

Date                                  datetime64[ns]
RTGS_Vol                                     float64
RTGS_Val                                     float64
NEFT_Vol                                     float64
NEFT_Val                                     float64
AePS_Vol                                     float64
AePS_Val                                     float64
UPI_Vol                                      float64
UPI_Val                                      float64
IMPS_Vol                                     float64
IMPS_Val                                     float64
NACH Credit_Vol                              float64
NACH Credit_Val                              float64
NACH Debit_Vol                               float64
NACH Debit_Val                               float64
NETC_Vol                                     float64
NETC_Val                                     float64
BBPS_Vol                                     float64
BBPS_Val                                      object
CTS_Vol                                       object
CTS_Val                                       object
CreditCard_POS_Vol                           float64
CreditCard_POS_Val                            object
CreditCard_Ecommerce_Vol                     float64
CreditCard_Ecommerce_Val                     float64
DebitCard_POS_Vol                            float64
DebitCard_POS_Val                            float64
DebitCard_Ecommerce_Vol                      float64
DebitCard_Ecommerce_Val                      float64
PPI_POS_Vol                                  float64
PPI_POS_Val                                  float64
PPI_Ecommerce_Vol                            float64
PPI_Ecommerce_Val                            float64
NFS_ATM_Vol                                  float64
NFS_ATM_Val                                  float64
AePS_microATM_Vol                            float64
AePS_microATM_Val                            float64
Government_Securities_Clearing_Vol            object
Government_Securities_Clearing_Val            object
Forex_Clearing_Vol                            object
Forex_Clearing_Val                            object
Rupee_Derivatives_Vol                         object
Rupee_Derivatives_Val                         object
dtype: object

In [226]:
cols = [
    'Government_Securities_Clearing_Vol',
    'Government_Securities_Clearing_Val',
    'Forex_Clearing_Vol',
    'Forex_Clearing_Val',
    'Rupee_Derivatives_Vol',
    'Rupee_Derivatives_Val'
]

for col in cols:
    print(col)
    print(df[col].value_counts(dropna=False).head(10))
    print()

Government_Securities_Clearing_Vol
Government_Securities_Clearing_Vol
h          231
0.00138      3
0.0826       3
0            3
0.00152      3
0.0866       2
0.10629      2
0.00164      2
0.0549       2
0.00141      2
Name: count, dtype: int64

Government_Securities_Clearing_Val
Government_Securities_Clearing_Val
h         129
841.27      2
874.6       2
867.29      1
716.68      1
958.57      1
887.23      1
929.57      1
932.75      1
920.38      1
Name: count, dtype: int64

Forex_Clearing_Vol
Forex_Clearing_Vol
h           231
0            86
0.165125      2
0.151995      2
0.1409        2
0.136935      2
0.13787       2
0.15548       2
0.13445       1
0.13212       1
Name: count, dtype: int64

Forex_Clearing_Val
Forex_Clearing_Val
h                231
0                 50
895581.193         1
857976.847905      1
13947.13           1
888486.581         1
879615.077049      1
888945.091         1
898177.724         1
901447.555         1
Name: count, dtype: int64

Rupee_Derivatives_Vol
Rupee_Derivatives_Vol
h          231
0           64
0.00424      4
0.00472      4
0.0054       3
0.0051       3
0.00385      3
0.00531      3
0.00207      3
0.00476      3
Name: count, dtype: int64

Rupee_Derivatives_Val
Rupee_Derivatives_Val
h            231
0             73
43985          2
510884.56      1
468416.01      1
504607.84      1
452771.61      1
517587.3       1
319713.35      1
346560.9       1
Name: count, dtype: int64

In [227]:
df['GSC_Holiday'] = df['Government_Securities_Clearing_Vol'].eq('h')

In [228]:
for col in cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [229]:
df['BBPS_Val'] = pd.to_numeric(df['BBPS_Val'], errors='coerce')
df["CTS_Vol"] = pd.to_numeric(df['CTS_Vol'],errors='coerce')
df["CTS_Val"] = pd.to_numeric(df['CTS_Val'],errors='coerce')

In [230]:
df["CreditCard_POS_Val"] = pd.to_numeric(df['CreditCard_POS_Val'],errors ="coerce")

In [231]:
df['GSC_Holiday'] = df['Government_Securities_Clearing_Vol'].eq('h')

In [232]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 868 entries, 0 to 867
Data columns (total 44 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Date                                868 non-null    datetime64[ns]
 1   RTGS_Vol                            868 non-null    float64
 2   RTGS_Val                            868 non-null    float64
 3   NEFT_Vol                            868 non-null    float64
 4   NEFT_Val                            868 non-null    float64
 5   AePS_Vol                            868 non-null    float64
 6   AePS_Val                            868 non-null    float64
 7   UPI_Vol                             868 non-null    float64
 8   UPI_Val                             868 non-null    float64
 9   IMPS_Vol                            868 non-null    float64
 10  IMPS_Val                            868 non-null    float64
 11  NACH Credit_Vol                     868 non-null    float64
 12  NACH Credit_Val                     868 non-null    float64
 13  NACH Debit_Vol                      868 non-null    float64
 14  NACH Debit_Val                      868 non-null    float64
 15  NETC_Vol                            868 non-null    float64
 16  NETC_Val                            868 non-null    float64
 17  BBPS_Vol                            868 non-null    float64
 18  BBPS_Val                            854 non-null    float64
 19  CTS_Vol                             683 non-null    float64
 20  CTS_Val                             762 non-null    float64
 21  CreditCard_POS_Vol                  868 non-null    float64
 22  CreditCard_POS_Val                  789 non-null    float64
 23  CreditCard_Ecommerce_Vol            487 non-null    float64
 24  CreditCard_Ecommerce_Val            868 non-null    float64
 25  DebitCard_POS_Vol                   868 non-null    float64
 26  DebitCard_POS_Val                   868 non-null    float64
 27  DebitCard_Ecommerce_Vol             487 non-null    float64
 28  DebitCard_Ecommerce_Val             868 non-null    float64
 29  PPI_POS_Vol                         868 non-null    float64
 30  PPI_POS_Val                         868 non-null    float64
 31  PPI_Ecommerce_Vol                   487 non-null    float64
 32  PPI_Ecommerce_Val                   868 non-null    float64
 33  NFS_ATM_Vol                         868 non-null    float64
 34  NFS_ATM_Val                         868 non-null    float64
 35  AePS_microATM_Vol                   868 non-null    float64
 36  AePS_microATM_Val                   868 non-null    float64
 37  Government_Securities_Clearing_Vol  637 non-null    float64
 38  Government_Securities_Clearing_Val  739 non-null    float64
 39  Forex_Clearing_Vol                  637 non-null    float64
 40  Forex_Clearing_Val                  637 non-null    float64
 41  Rupee_Derivatives_Vol               637 non-null    float64
 42  Rupee_Derivatives_Val               637 non-null    float64
 43  GSC_Holiday                         868 non-null    bool
dtypes: bool(1), datetime64[ns](1), float64(42)
memory usage: 292.6 KB

In [233]:
df.isnull().sum().sort_values(ascending=False)

CreditCard_Ecommerce_Vol              381
PPI_Ecommerce_Vol                     381
DebitCard_Ecommerce_Vol               381
Government_Securities_Clearing_Vol    231
Forex_Clearing_Val                    231
Rupee_Derivatives_Vol                 231
Forex_Clearing_Vol                    231
Rupee_Derivatives_Val                 231
CTS_Vol                               185
Government_Securities_Clearing_Val    129
CTS_Val                               106
CreditCard_POS_Val                     79
BBPS_Val                               14
IMPS_Val                                0
IMPS_Vol                                0
UPI_Val                                 0
NACH Credit_Vol                         0
AePS_Val                                0
AePS_Vol                                0
NEFT_Val                                0
NEFT_Vol                                0
RTGS_Val                                0
RTGS_Vol                                0
Date                                    0
UPI_Vol                                 0
NETC_Val                                0
NACH Credit_Val                         0
NACH Debit_Vol                          0
DebitCard_POS_Val                       0
DebitCard_POS_Vol                       0
CreditCard_Ecommerce_Val                0
CreditCard_POS_Vol                      0
NETC_Vol                                0
NACH Debit_Val                          0
BBPS_Vol                                0
DebitCard_Ecommerce_Val                 0
AePS_microATM_Vol                       0
NFS_ATM_Val                             0
NFS_ATM_Vol                             0
PPI_Ecommerce_Val                       0
PPI_POS_Val                             0
PPI_POS_Vol                             0
AePS_microATM_Val                       0
GSC_Holiday                             0
dtype: int64

In [234]:
df['Date'].min(), df['Date'].max()

(Timestamp('2024-04-01 00:00:00'), Timestamp('2026-08-16 00:00:00'))

In [235]:
numeric_cols = df.select_dtypes(include='number').columns

negative_counts = (df[numeric_cols] < 0).sum()

negative_counts[negative_counts > 0]

Series([], dtype: int64)

In [236]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Date,868,2025-06-08 11:59:59.999999744,2024-04-01 00:00:00,2024-11-03 18:00:00,2025-06-08 12:00:00,2026-01-11 06:00:00,2026-08-16 00:00:00,NaN
RTGS_Vol,868.0,9.16936,0.76502,5.86304,10.466685,12.196715,25.83312,4.372282
RTGS_Val,868.0,601067.017931,11349.224347,145092.231784,736015.227961,871354.567423,2454674.054413,402658.178188
NEFT_Vol,868.0,272.238696,26.92938,223.07651,275.180455,314.23321,579.27818,74.532831
NEFT_Val,868.0,132017.351428,14445.232629,82060.755881,144969.151157,170566.339505,597085.590509,72428.472637
AePS_Vol,868.0,0.678275,0.264,0.569,0.669,0.768,1.579,0.168516
AePS_Val,868.0,22.034551,9.51,18.635,20.975,24.13,48.16,5.426678
UPI_Vol,868.0,6132.176555,4081.77,5217.925,6120.32,7054.71,8487.91,1058.838242
UPI_Val,868.0,81660.571106,45136.0,70375.195,80482.98,92678.5275,131735.46,15723.106642
IMPS_Vol,868.0,140.549401,84.74,123.745,139.25,155.445,256.87,23.920108
IMPS_Val,868.0,20692.716359,9840.09,18329.3475,21144.66,23889.7525,35785.9,4687.119256
NACH Credit_Vol,868.0,136.735668,0.25,72.2075,117.305,173.36,1403.8,125.048201
NACH Credit_Val,868.0,6768.265046,127.08,3795.6275,6809.13,8941.4375,32252.03,4550.206604
NACH Debit_Vol,868.0,58.142684,3.47,17.2375,31.49,74.125,351.16,64.735633
NACH Debit_Val,868.0,6995.223906,310.84,3456.3275,5176.72,7609.495,41810.78,6749.43279
NETC_Vol,868.0,118.403848,72.68,111.645,118.165,125.22,158.25,10.697573
NETC_Val,868.0,216.807972,127.18,199.15,220.635,234.7825,269.7,23.232352
BBPS_Vol,868.0,78.950534,35.53,70.109062,79.512915,91.032403,113.30653,15.542632
BBPS_Val,854.0,1757.291553,0.0,0.04,1466.605,3228.51,7703.655114,1813.595218
CTS_Vol,683.0,19.956105,0.0,17.73,19.82,22.32,39.48,5.705734
CTS_Val,762.0,14734.419105,269.07,4132.65673,7185.285699,24573.775,56817.05,11228.334922
CreditCard_POS_Vol,868.0,33.212234,16.45799,28.510855,30.49267,32.853185,69.40652,8.505747
CreditCard_POS_Val,789.0,10581.433892,0.0,1401.659861,1729.333081,23980.64,53998.5,12225.444586
CreditCard_Ecommerce_Vol,487.0,44.022134,18.60503,33.988915,42.22641,46.170065,94.62309,12.799745
CreditCard_Ecommerce_Val,868.0,2470.090649,834.352152,1510.269459,2098.007753,3115.858393,8416.667662,1169.519739
DebitCard_POS_Vol,868.0,24.899508,13.33722,20.777783,23.54573,27.943037,57.09751,5.796134
DebitCard_POS_Val,868.0,1789.910977,369.077256,701.748474,1029.053186,2756.445852,10411.83544,1445.217519
DebitCard_Ecommerce_Vol,487.0,11.20483,4.30069,9.08683,10.61079,12.8516,28.59252,3.195924
DebitCard_Ecommerce_Val,868.0,528.635102,123.949874,400.854072,527.294938,623.880658,1319.733059,189.361367
PPI_POS_Vol,868.0,5.794104,0.62972,3.857915,6.04498,8.101762,12.4747,2.748303
PPI_POS_Val,868.0,185.588888,9.603303,17.650017,21.341776,378.323463,814.417082,208.884473
PPI_Ecommerce_Vol,487.0,1.190177,0.56492,0.935065,1.18093,1.350295,2.42013,0.371943
PPI_Ecommerce_Val,868.0,42.87172,5.380776,21.111364,30.060057,58.68403,172.378172,31.119934
NFS_ATM_Vol,868.0,90.84068,66.39,81.8525,89.95,98.41,142.43,11.996692
NFS_ATM_Val,868.0,2369.884049,7.26764,66.930823,3316.465,4221.5625,6984.18,2115.119366
AePS_microATM_Vol,868.0,32.154539,17.17,27.5275,31.145,35.1925,70.91,6.663376
AePS_microATM_Val,868.0,2182.671774,468.43,781.9,1008.1,3730.4775,5912.82,1597.583353
Government_Securities_Clearing_Vol,637.0,0.072951,0.0,0.06439,0.07842,0.08858,0.17706,0.029177
Government_Securities_Clearing_Val,739.0,348394.208533,0.0,840.655,1314.74,781855.8145,1049875.083846,395965.253231
Forex_Clearing_Vol,637.0,0.121362,0.0,0.093185,0.131625,0.154455,0.356845,0.06561
Forex_Clearing_Val,637.0,589952.372477,0.0,315572.2,526016.53,903859.71195,2340792.5,371544.552025
Rupee_Derivatives_Vol,637.0,0.005792,0.0,0.00378,0.00548,0.00766,0.01673,0.003372
Rupee_Derivatives_Val,637.0,261906.66764,0.0,28477.92,50465.93,493756.4,3077848.74,405072.75898

In [237]:
volume_cols = [col for col in df.columns if col.endswith('_Vol')]
volume_cols

['RTGS_Vol',
 'NEFT_Vol',
 'AePS_Vol',
 'UPI_Vol',
 'IMPS_Vol',
 'NACH Credit_Vol',
 'NACH Debit_Vol',
 'NETC_Vol',
 'BBPS_Vol',
 'CTS_Vol',
 'CreditCard_POS_Vol',
 'CreditCard_Ecommerce_Vol',
 'DebitCard_POS_Vol',
 'DebitCard_Ecommerce_Vol',
 'PPI_POS_Vol',
 'PPI_Ecommerce_Vol',
 'NFS_ATM_Vol',
 'AePS_microATM_Vol',
 'Government_Securities_Clearing_Vol',
 'Forex_Clearing_Vol',
 'Rupee_Derivatives_Vol']

In [238]:
value_cols = [col for col in df.columns if col.endswith('_Val')]
value_cols

['RTGS_Val',
 'NEFT_Val',
 'AePS_Val',
 'UPI_Val',
 'IMPS_Val',
 'NACH Credit_Val',
 'NACH Debit_Val',
 'NETC_Val',
 'BBPS_Val',
 'CTS_Val',
 'CreditCard_POS_Val',
 'CreditCard_Ecommerce_Val',
 'DebitCard_POS_Val',
 'DebitCard_Ecommerce_Val',
 'PPI_POS_Val',
 'PPI_Ecommerce_Val',
 'NFS_ATM_Val',
 'AePS_microATM_Val',
 'Government_Securities_Clearing_Val',
 'Forex_Clearing_Val',
 'Rupee_Derivatives_Val']

In [239]:
total_volume = df[volume_cols].sum().sort_values(ascending=False)
print("Total Transaction Count:")
print((total_volume*100000).apply(lambda x:f"⇄ {x:,.0f}"))

Total Transaction Count:
UPI_Vol                               ⇄ 532,272,925,000
NEFT_Vol                               ⇄ 23,630,318,810
IMPS_Vol                               ⇄ 12,199,688,000
NACH Credit_Vol                        ⇄ 11,868,656,000
NETC_Vol                               ⇄ 10,277,454,000
NFS_ATM_Vol                             ⇄ 7,884,971,000
BBPS_Vol                                ⇄ 6,852,906,309
NACH Debit_Vol                          ⇄ 5,046,785,000
CreditCard_POS_Vol                      ⇄ 2,882,821,948
AePS_microATM_Vol                       ⇄ 2,791,014,000
DebitCard_POS_Vol                       ⇄ 2,161,277,295
CreditCard_Ecommerce_Vol                ⇄ 2,143,877,942
CTS_Vol                                 ⇄ 1,363,002,000
RTGS_Vol                                  ⇄ 795,900,474
DebitCard_Ecommerce_Vol                   ⇄ 545,675,242
PPI_POS_Vol                               ⇄ 502,928,208
AePS_Vol                                   ⇄ 58,874,300
PPI_Ecommerce_Vol                          ⇄ 57,961,643
Forex_Clearing_Vol                          ⇄ 7,730,749
Government_Securities_Clearing_Vol          ⇄ 4,646,993
Rupee_Derivatives_Vol                         ⇄ 368,919
dtype: object

In [240]:
daily_avg_transactions = (df[volume_cols].mean() * 100000).sort_values(ascending=False)
print(daily_avg_transactions.apply(lambda x: f"⇄ {x:,.0f}"))

UPI_Vol                               ⇄ 613,217,656
NEFT_Vol                               ⇄ 27,223,870
IMPS_Vol                               ⇄ 14,054,940
NACH Credit_Vol                        ⇄ 13,673,567
NETC_Vol                               ⇄ 11,840,385
NFS_ATM_Vol                             ⇄ 9,084,068
BBPS_Vol                                ⇄ 7,895,053
NACH Debit_Vol                          ⇄ 5,814,268
CreditCard_Ecommerce_Vol                ⇄ 4,402,213
CreditCard_POS_Vol                      ⇄ 3,321,223
AePS_microATM_Vol                       ⇄ 3,215,454
DebitCard_POS_Vol                       ⇄ 2,489,951
CTS_Vol                                 ⇄ 1,995,611
DebitCard_Ecommerce_Vol                 ⇄ 1,120,483
RTGS_Vol                                  ⇄ 916,936
PPI_POS_Vol                               ⇄ 579,410
PPI_Ecommerce_Vol                         ⇄ 119,018
AePS_Vol                                   ⇄ 67,828
Forex_Clearing_Vol                         ⇄ 12,136
Government_Securities_Clearing_Vol          ⇄ 7,295
Rupee_Derivatives_Vol                         ⇄ 579
dtype: object

In [241]:
total_value = df[value_cols].sum().sort_values(ascending=False)
print("Total Transaction Amount:")
print((total_value*10000000).apply(lambda x:f"₹{x:,.0f}"))

Total Transaction Amount:
RTGS_Val                              ₹5,217,261,715,642,705
Forex_Clearing_Val                    ₹3,757,996,612,681,246
Government_Securities_Clearing_Val    ₹2,574,633,201,055,788
Rupee_Derivatives_Val                 ₹1,668,345,472,864,250
NEFT_Val                              ₹1,145,910,610,390,965
UPI_Val                                 ₹708,813,757,200,000
IMPS_Val                                ₹179,612,778,000,000
CTS_Val                                 ₹112,276,273,583,903
CreditCard_POS_Val                       ₹83,487,513,404,423
NACH Debit_Val                           ₹60,718,543,500,000
NACH Credit_Val                          ₹58,748,540,600,000
CreditCard_Ecommerce_Val                 ₹21,440,386,833,357
NFS_ATM_Val                              ₹20,570,593,543,112
AePS_microATM_Val                        ₹18,945,591,000,000
DebitCard_POS_Val                        ₹15,536,427,280,895
BBPS_Val                                 ₹15,007,269,860,308
DebitCard_Ecommerce_Val                   ₹4,588,552,686,528
NETC_Val                                  ₹1,881,893,200,000
PPI_POS_Val                               ₹1,610,911,549,953
PPI_Ecommerce_Val                           ₹372,126,528,533
AePS_Val                                    ₹191,259,900,000
dtype: object

In [242]:
daily_Avg_tran_Amt = df[value_cols].mean().sort_values(ascending=False)*10000000
print(daily_Avg_tran_Amt.apply(lambda x: f"₹{x:,.0f}"))

RTGS_Val                              ₹6,010,670,179,312
Forex_Clearing_Val                    ₹5,899,523,724,774
Government_Securities_Clearing_Val    ₹3,483,942,085,326
Rupee_Derivatives_Val                 ₹2,619,066,676,396
NEFT_Val                              ₹1,320,173,514,275
UPI_Val                                 ₹816,605,711,060
IMPS_Val                                ₹206,927,163,594
CTS_Val                                 ₹147,344,191,055
CreditCard_POS_Val                      ₹105,814,338,916
NACH Debit_Val                           ₹69,952,239,055
NACH Credit_Val                          ₹67,682,650,461
CreditCard_Ecommerce_Val                 ₹24,700,906,490
NFS_ATM_Val                              ₹23,698,840,487
AePS_microATM_Val                        ₹21,826,717,742
DebitCard_POS_Val                        ₹17,899,109,771
BBPS_Val                                 ₹17,572,915,527
DebitCard_Ecommerce_Val                   ₹5,286,351,021
NETC_Val                                  ₹2,168,079,724
PPI_POS_Val                               ₹1,855,888,882
PPI_Ecommerce_Val                           ₹428,717,199
AePS_Val                                    ₹220,345,507
dtype: object

In [243]:
upi_avg_amount_per_tran = (total_value['UPI_Val'] / total_volume['UPI_Vol']) * 100
print(f"Average UPI Amount: ₹{round(upi_avg_amount_per_tran,2)}")

Average UPI Amount: ₹1331.67

In [244]:
rtgs_avg_amount = (total_value['RTGS_Val'] / total_volume['RTGS_Vol']) * 100
print(f"Average RTGS Amount: ₹{rtgs_avg_amount:,.0f}")

Average RTGS Amount: ₹6,555,168

In [245]:
neft_avg_amount = (total_value['NEFT_Val'] / total_volume['NEFT_Vol']) * 100
print(f"Average NEFT Amount: ₹{neft_avg_amount:,.0f}")

Average NEFT Amount: ₹48,493

In [246]:
imps_avg_amount = (total_value['IMPS_Val'] / total_volume['IMPS_Vol']) * 100
print(f"Average IMPS Amount: ₹{imps_avg_amount:,.0f}")

Average IMPS Amount: ₹14,723

In [269]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Month_Name'] = df['Date'].dt.month_name()

In [258]:
df['FY'] = df['Date'].dt.year.where(
    df['Date'].dt.month < 4,
    df['Date'].dt.year + 1
).astype(str)

df['FY'] = "FY"+((df['FY'].astype(int)-1)).astype(str)+"-"+(df['FY'].str[-2:])

In [270]:
df.columns.to_list()

['Date',
 'RTGS_Vol',
 'RTGS_Val',
 'NEFT_Vol',
 'NEFT_Val',
 'AePS_Vol',
 'AePS_Val',
 'UPI_Vol',
 'UPI_Val',
 'IMPS_Vol',
 'IMPS_Val',
 'NACH Credit_Vol',
 'NACH Credit_Val',
 'NACH Debit_Vol',
 'NACH Debit_Val',
 'NETC_Vol',
 'NETC_Val',
 'BBPS_Vol',
 'BBPS_Val',
 'CTS_Vol',
 'CTS_Val',
 'CreditCard_POS_Vol',
 'CreditCard_POS_Val',
 'CreditCard_Ecommerce_Vol',
 'CreditCard_Ecommerce_Val',
 'DebitCard_POS_Vol',
 'DebitCard_POS_Val',
 'DebitCard_Ecommerce_Vol',
 'DebitCard_Ecommerce_Val',
 'PPI_POS_Vol',
 'PPI_POS_Val',
 'PPI_Ecommerce_Vol',
 'PPI_Ecommerce_Val',
 'NFS_ATM_Vol',
 'NFS_ATM_Val',
 'AePS_microATM_Vol',
 'AePS_microATM_Val',
 'Government_Securities_Clearing_Vol',
 'Government_Securities_Clearing_Val',
 'Forex_Clearing_Vol',
 'Forex_Clearing_Val',
 'Rupee_Derivatives_Vol',
 'Rupee_Derivatives_Val',
 'GSC_Holiday',
 'Year',
 'Month',
 'FY',
 'Month_Name']

In [260]:
upi_trend_yearly = df.groupby("FY")['UPI_Vol'].sum()*100000
print("------ UPI-TREND --------\n")
print(upi_trend_yearly.apply(lambda x:f"⇄ {x:,.0f}"))

------ UPI-TREND --------

FY
FY2024-25    ⇄ 185,866,025,000
FY2025-26    ⇄ 241,616,886,000
FY2026-27    ⇄ 104,790,014,000
Name: UPI_Vol, dtype: object

In [265]:
rtgs_trend_yearly = df.groupby("FY")['RTGS_Vol'].sum()*100000
print("------ RTGS-TREND --------\n")
print(rtgs_trend_yearly.apply(lambda x : f"{x:,.0f}"))

------ RTGS-TREND --------

FY
FY2024-25    302,454,580
FY2025-26    349,978,862
FY2026-27    143,467,032
Name: RTGS_Vol, dtype: object

In [266]:
imps_trend_yearly = df.groupby("FY")['IMPS_Vol'].sum()*100000
print("------ IMPS-TREND --------\n")
print(imps_trend_yearly.apply(lambda x : f"{x:,.0f}"))

------ IMPS-TREND --------

FY
FY2024-25    5,624,968,000
FY2025-26    4,943,109,000
FY2026-27    1,631,611,000
Name: IMPS_Vol, dtype: object

In [267]:
neft_trend_yearly = df.groupby("FY")['NEFT_Vol'].sum()*100000
print("------ NEFT-TREND --------\n")
print(neft_trend_yearly.apply(lambda x : f"{x:,.0f}"))

------ NEFT-TREND --------

FY
FY2024-25     9,619,804,750
FY2025-26    10,099,615,490
FY2026-27     3,910,898,570
Name: NEFT_Vol, dtype: object

In [272]:
df.to_csv('Rbi_Analysis_data.csv', index=False)
print("Rbi_Analysis_data file save successfully")

Rbi_Analysis_data file save successfully